#!/bin/bash

# Replace SOURCE_DIR and DESTINATION_DIR with the source and destination directories, respectively
SOURCE_DIR="/path/to/source/directory"
DESTINATION_DIR="/path/to/destination/directory"

# Copy all files from the source directory to the destination directory
cp -r "$SOURCE_DIR"/* "$DESTINATION_DIR"/
